# 🐶 Proyecto Big Data: Inteligencia de Mercado en Productos para Mascotas


### Contexto del Proyecto

El mercado de productos para mascotas ha experimentado un crecimiento sostenido durante los últimos años. Las empresas del sector necesitan comprender continuamente:

- cómo cambian los precios,
- qué marcas dominan el mercado,
- cuáles productos poseen mejor valoración,
- qué formatos ofrecen mejor relación precio/calidad,
- y cómo se segmentan los consumidores y productos dentro del ecosistema digital.

Actualmente muchas organizaciones toman estas decisiones de forma manual, revisando páginas web una por una, sin automatización ni almacenamiento histórico de datos, lo que dificulta identificar tendencias y patrones relevantes para la toma de decisiones eégicas.

---

# 🎯 Objetivo del Proyecto

Desarrollar un pipeline de Big Data capaz de:

- Capturar información desde sitios web relacionados con productos para mascotas.
- Almacenar grandes volúmenes de datos en MongoDB Atlas.
- Procesar y limpiar datos utilizando Apache Spark.
- Realizar análisis exploratorio de datos (EDA).
- Aplicar técnicas de segmentación mediante Machine Learning.
- Generar conocimiento útil para apoyar denes organizacionales.

---

# ❓ Pregunta de Negocio

## ¿Cómo se segmenta el mercado de productos para mascotas según variables como:

- precio,
- marca,
- formato,
- rating,
- oones,
- y relación precio/calidad?

---

# 📊 Objetivos Analíticos

Durante el desarrollo del proyecto se buscará responder preguntas como:

- ¿Qué marcas presentan precios más elevados?
- ¿Qué productos tienen mejor valoración por parte de los usuarios?
- ¿Existen productos sobrevalorados o subvalorados?
- ¿Qué segmentos de mercado pueden identificarse?
- ¿Qué características poseen los productos premium?
- ¿Cómo varía el precio según formato o cría?
- ¿Existe relación entre precio y rating?

---

# 🧠 Relación con Big Data

Este proyecto aborda directamente las características fundamentales del Big Data:

## 🔹 Volumen
Se trabajará con cientos o miles de registros provenientes de scraping web y almacenamiento en MongoDB Atlas.

## 🔹 Variedad
Los datos contienen distintos tipos de atributos:

- texto,
- números,
- categorías,
- ratings,
- formatos,
- fechas,
- precios,
- opiniones.

## 🔹 Veracidad
Los datos deberán ser limpiados y validados mediante:

- tratamiento de nulos,
- eliminación de duplicados,
- corrección de formatos,
- detección de outliers.

## 🔹 Velocidad
El mercado online cambia constantemente, por lo que el 
ing debe poder ejecutarse periódicamente para mantener información actualizada.

---

# ⚙️ Pipeline Tecnológico del Proyecto

El flujo general del proyecto será:

```text
Sitio Web (Tiendanimal)
            ↓
Scraping Web
            ↓
MongoDB Atlas (Raw Data)
            ↓
Apache Spark
            ↓
EDA y Limpieza
            ↓
MongoDB Processed Data
            ↓
Clustering y Machine Learning
            ↓
Generación de conocimiento

## Etapa 1: Captura y almacenamiento de datos crudos
En este notebook se realizará:

- Extracción de datos desde una fuente web relacionada con productos de mascotas.
- Construcción de documentos JSON con al menos 8 campos.
- Almacenamiento en MongoDB Atlas.
- Creación de la colección `Mercado_Mascotas_Raw`.

Este notebook corresponde a la etapa **Scraper/Raw** del pipeline.

# Paso 2: Definir estructura de proyecto 

Proyecto_Mascotas/
│
├── scraperss/
│   └── scraper_tiendanimal.py
│
├── .env
└── requirements.txt

### Paso 2: Configurar MongoDB Atlas

Crear el archivo .env con las credenciales de conexión:

MONGO_URI=mongodb+srv://USUARIO:CONTRASENA@cluster.mongodb.net/?retryWrites=true&w=majority

MONGO_DB=MascotasDB

MONGO_COLLECTION=Mercado_Mascotas_Raw

## Etapa 2: Desarrollo del scraper

El archivo .py será el encargado de hacer el scraping.

Ese archivo tendrá el código dividido por pasos:

- 1 Importar librerías.
- 2 Configurar conexión con MongoDB Atlas.
- 3 Configurar la fuente web.
- 4 Obtener el HTML del sitio.
- 5 Detectar posibles bloqueos.
- 6 Extraer información de productos.tos.

### Paso 1: Importar librerías

Se importan las librerías necesarias para:

- Conectarse a la web.
- Procesar HTML.
- Conectarse a MongoDB Atlas.
- Registrar fecha y hora de captura.

In [41]:
import requests
import time
import certifi
import re
import pandas as pd

from bs4 import BeautifulSoup
from pymongo import MongoClient, UpdateOne

## Paso 2: Configurar conexión segura a MongoDB Atlas

La guía del proyecto solicita trabajar con MongoDB Atlas y no con MongoDB local para la persistencia final.

En una versión profesional, la URI debe guardarse en un archivo `.env`.
Para esta prueba controlada, se usará una variable `uri`.

In [42]:
uri = "mongodb+srv://yhadfeg_db_user:3192Yahima@cluster0.8pbh7yw.mongodb.net/ProyectoSemana9?retryWrites=true&w=majority"

client = MongoClient(
    uri,
    tlsCAFile=certifi.where(),
    serverSelectionTimeoutMS=10000
)

db = client["ProyectoSemana9"]
coleccion_raw = db["Mercado_Mascotas_Raw"]

try:
    client.server_info()
    print("Conexión exitosa con MongoDB Atlas")
except Exception as e:
    print("Error de conexión:", e)

Conexión exitosa con MongoDB Atlas

## Paso 3: Definir fuente web y estructura esperada del docu

Se usará una página relacionada con productos para mascotas.  
El objetivo es obtener productos y transformarlos a una estructura común para análisis posterior.

Estructura esperada del documento:

```python
{
    "sku_id": "...",
    "marca": "...",
    "precio_raw": "...",
    "formato_raw": "...",
    "rating": "...",
    "opiniones": "...",
    "tienda": "Tiendanimal",
    "fecha_captura": "..."
}

In [43]:
url = "https://www.tiendanimal.es/perros/pienso-para-perros/"

headers = {
    "User-Agent": (
        "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
        "AppleWebKit/537.36 (KHTML, like Gecko) "
        "Chrome/120.0.0.0 Safari/537.36"
    ),
    "Accept-Language": "es-ES,es;q=0.9,en;q=0.8"
}

respuesta = requests.get(url, headers=headers, timeout=30)

print("Status Code:", respuesta.status_code)
print("Tamaño del HTML:", len(respuesta.text))
print("URL final:", respuesta.url)

Status Code: 200
Tamaño del HTML: 833790
URL final: https://www.tiendanimal.es/perros/pienso-para-perros/

## Paso 5: Crear una extracción inicial y verificar si hay bloqueos
De haber bloqueos usar Selenium

In [44]:
# revisar si hay bloqueo
html = respuesta.text.lower()

palabras_bloqueo = ["captcha", "robot", "access denied", "forbidden", "unusual traffic"]

bloqueo_detectado = any(palabra in html for palabra in palabras_bloqueo)

if bloqueo_detectado:
    print("Posible bloqueo detectado. Puede requerir intervención humana.")
else:
    print("No se detectan señales evidentes de bloqueo en el HTML.")

Posible bloqueo detectado. Puede requerir intervención humana.

In [45]:
# Como se detectó un posible bloqueo 
# Ejecutar la celda Selenium

from selenium import webdriver
from selenium.webdriver.chrome.service import Service
from selenium.webdriver.chrome.options import Options
from webdriver_manager.chrome import ChromeDriverManager
import time

options = Options()

options.add_argument("--no-sandbox")
options.add_argument("--disable-dev-shm-usage")
options.add_argument("--disable-gpu")

driver = webdriver.Chrome(
    service=Service(ChromeDriverManager().install()),
    options=options
)
print("Abrir el entorno visual...")

driver.get(url)

print("http://localhost:6080/vnc.html")

print("Navegador abierto")

print("Revisar la página manualmente y resuleva posibles conflictos...")

print("Conflictos resultos....continúe con el scraping")

Abrir el entorno visual...
http://localhost:6080/vnc.html
Navegador abierto
Revisar la página manualmente y resuleva posibles conflictos...
Conflictos resultos....continúe con el scraping

## Paso 6: Construir documentos

Cada elemento se transforma a un documento JSON con 8 campos mínimos.

Aunque la estructura mínima solicitada tiene 8 campos, agregaremos responsable, url_fuente y categoria para que quede mejor alineado con el proyecto.

In [46]:
# construir productos desde Selenium
tarjetas = soup.find_all("div", class_="isk-product-card")

print("Tarjetas de producto encontradas:", len(tarjetas))

productos = []
fecha_actual = time.strftime("%Y-%m-%d %H:%M:%S")

for i, tarjeta in enumerate(tarjetas, start=1):

    texto_completo = tarjeta.get_text(" ", strip=True)

    # Nombre del producto
    nombre_tag = tarjeta.find(class_="isk-product-card__headline")
    nombre = nombre_tag.get_text(" ", strip=True) if nombre_tag else None

    # Rating y opiniones
    reviews_tag = tarjeta.find(class_="isk-product-card__reviews")
    reviews_text = reviews_tag.get_text(" ", strip=True) if reviews_tag else ""

    rating = None
    opiniones = None

    match_reviews = re.search(
        r"(\d+[.,]?\d*)\s*estrellas\s*con\s*(\d+)\s*opiniones",
        reviews_text,
        re.IGNORECASE
    )

    if match_reviews:
        rating = float(match_reviews.group(1).replace(",", "."))
        opiniones = int(match_reviews.group(2))

    # Precios y formato
    precios_tag = tarjeta.find(class_="isk-product-card__prices")
    precios_text = precios_tag.get_text(" ", strip=True) if precios_tag else ""

    precio_raw = None
    formato_raw = None

    match_precio = re.search(
        r"Precio\s+de\s+([0-9]+[.,][0-9]{2}€(?:\s*a\s*[0-9]+[.,][0-9]{2}€)?)",
        precios_text,
        re.IGNORECASE
    )

    if match_precio:
        precio_raw = match_precio.group(1)

    match_formato = re.search(
        r"([0-9]+[.,][0-9]{2}€\s*el\s*kg|Desde\s+[0-9]+[.,][0-9]{2}€\s*/\s*kg|[0-9]+\s+opciones\s+de\s+peso)",
        precios_text,
        re.IGNORECASE
    )

    if match_formato:
        formato_raw = match_formato.group(1)

    # SKU interno académico
    sku_id = f"TD_{i:05d}"

    producto = {
        "sku_id": sku_id,
        "marca": nombre.split()[0] if nombre else "Sin_marca",
        "precio_raw": precio_raw,
        "formato_raw": formato_raw if formato_raw else sku_id,
        "rating": rating,
        "opiniones": opiniones,
        "tienda": "Tiendanimal",
        "fecha_captura": fecha_actual,

        # Campos adicionales útiles para la guía del proyecto
        "nombre_producto": nombre,
        "categoria": "Pienso para perros",
        "url_fuente": url,
        "responsable": "Yahima",
        "texto_crudo": texto_completo
    }

    productos.append(producto)

Tarjetas de producto encontradas: 32

# Paso 7: Validación previa de datos

Antes de insertar información en MongoDB Atlas es importante revisar:

- estructura de los documentos,
- calidad del scraping,
- campos nulos,
- ejemplos reales,
- cantidad de registros,
- consistencia de los datos.

Esto permite evitar almacenar información incorrecta o incompleta en el pipeline Big Data.

In [47]:
print("Productos construidos correctamente:", len(productos))

# Convertir la lista de diccionarios en una tabla para revisar visualmente
df_preview = pd.DataFrame(productos)

print("\nVista previa de los primeros 10 productos:")
display(df_preview.head(10))


# 1. Validar cantidad de registros
print("\n1. Validación de cantidad de registros")
print("Total de productos capturados:", len(df_preview))

if len(df_preview) == 0:
    print("No hay productos capturados. No se debe insertar en MongoDB.")
else:
    print("Hay productos capturados.")

# 2. Validar estructura esperada

print("\n2. Validación de estructura esperada")

campos_obligatorios = [
    "sku_id",
    "marca",
    "precio_raw",
    "formato_raw",
    "rating",
    "opiniones",
    "tienda",
    "fecha_captura"
]

campos_faltantes = [
    campo for campo in campos_obligatorios
    if campo not in df_preview.columns
]

if campos_faltantes:
    print("Faltan campos obligatorios:", campos_faltantes)
else:
    print("Todos los campos obligatorios están presentes.")

# 3. Revisar valores nulos

print("\n3. Resumen de valores nulos por columna")
print(df_preview.isnull().sum())

campos_criticos = [
    "sku_id",
    "marca",
    "precio_raw",
    "formato_raw",
    "tienda",
    "fecha_captura"
]

nulos_criticos = df_preview[campos_criticos].isnull().sum().sum()

if nulos_criticos > 0:
    print("Hay nulos en campos críticos. Revisar antes de insertar.")
else:
    print("No hay nulos en campos críticos.")


# 4. Revisar duplicados
print("\n4. Validación de duplicados")

duplicados = df_preview.duplicated(
    subset=["sku_id", "tienda"]
).sum()

print("Duplicados encontrados:", duplicados)

if duplicados > 0:
    print("Hay duplicados. Se recomienda revisar la generación de sku_id.")
else:
    print("No se detectan duplicados por sku_id y tienda.")


# 5. Revisar productos con rating y opiniones
print("\n5. Productos con rating y opiniones")

productos_con_rating = df_preview[
    df_preview["rating"].notnull()
]

print("Productos con rating:", len(productos_con_rating))
print("Productos sin rating:", df_preview["rating"].isnull().sum())

display(
    productos_con_rating[
        ["nombre_producto", "rating", "opiniones", "precio_raw"]
    ].head(10)
)

# 6. Revisar una muestra completa tipo JSON

print("\n6. Ejemplo de documento que se insertaría en MongoDB Atlas")

if len(productos) > 0:
    print(productos[0])


# 7. Decisión final de calidad

print("\n7. Decisión final")

datos_suficientes = (
    len(df_preview) > 0
    and len(campos_faltantes) == 0
    and nulos_criticos == 0
    and duplicados == 0
)

if datos_suficientes:
    print("Los datos son suficientemente buenos para entrar al pipeline Big Data.")
    print("Puede continuar con la inserción/actualización en MongoDB Atlas.")
else:
    print("Los datos todavía NO son suficientemente buenos.")
    print("Revise estructura, nulos críticos o duplicados antes de insertar.")


# 8. Cerrar navegador

driver.quit()
print("\nNavegador cerrado correctamente.")

Productos construidos correctamente: 32

Vista previa de los primeros 10 productos:

,sku_id,marca,precio_raw,formato_raw,rating,opiniones,tienda,fecha_captura,nombre_producto,categoria,url_fuente,responsable,texto_crudo
0,TD_00001,Acana,19.99€ a 195.98€,5.76€ el kg,4.8,212.0,Tiendanimal,2026-05-14 22:36:27,Acana Adult pienso para perros,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,-5€ cada 35€ Patrocinado Patrocinado Acana Adu...
1,TD_00002,Salvaje,8.99€ a 37.98€,1.27€ el kg,NaN,NaN,Tiendanimal,2026-05-14 22:36:27,Salvaje Base Adultos Pollo pienso para perros,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,-40% en 2ª ud. Salvaje Base Adultos Pollo pien...
2,TD_00003,Nature's,28.59€ a 123.46€,5.14€ el kg,4.7,63.0,Tiendanimal,2026-05-14 22:36:27,Nature's Variety No Grain Adult Medium Maxi Sa...,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,¡Kilos Gratis! Patrocinado Patrocinado Nature'...
3,TD_00004,Hill's,41.99€ a 180.30€,9.02€ el kg,4.7,195.0,Tiendanimal,2026-05-14 22:36:27,Hill's Prescription Diet Food Sensitives z/d p...,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,¡Regalo! Hill's Prescription Diet Food Sensiti...
4,TD_00005,Nature's,26.49€ a 117.58€,4.90€ el kg,4.8,44.0,Tiendanimal,2026-05-14 22:36:27,Nature's Variety No Grain Adult Medium Maxi Po...,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,¡Kilos Gratis! Patrocinado Patrocinado Nature'...
5,TD_00006,Criadores,19.99€ a 123.48€,5.15€ el kg,4.6,290.0,Tiendanimal,2026-05-14 22:36:27,Criadores Dietetic Hipoalergénico Adulto piens...,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,-50% en 2ª ud. Criadores Dietetic Hipoalergéni...
6,TD_00007,Advance,30.19€ a 137.18€,6.86€ el kg,4.3,43.0,Tiendanimal,2026-05-14 22:36:27,Advance Veterinary Diets Hypoallergenic pienso...,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,¡Pack Ahorro! Patrocinado Patrocinado Advance ...
7,TD_00008,Orijen,27.99€ a 184.22€,8.08€ el kg,4.9,188.0,Tiendanimal,2026-05-14 22:36:27,Orijen Original pienso para perros,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,-15% Dto. Orijen Original pienso para perros 4...
8,TD_00009,Advance,30.19€ a 133.26€,5.55€ el kg,4.8,45.0,Tiendanimal,2026-05-14 22:36:27,Advance Veterinary Diets Urinary pienso para p...,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,¡Pack Ahorro! Patrocinado Patrocinado Advance ...
9,TD_00010,Salvaje,8.99€ a 49.38€,1.65€ el kg,NaN,NaN,Tiendanimal,2026-05-14 22:36:27,Salvaje Base Adultos Salmón pienso para perros,Pienso para perros,https://www.tiendanimal.es/perros/pienso-para-...,Yahima,-40% en 2ª ud. Salvaje Base Adultos Salmón pie...

1. Validación de cantidad de registros
Total de productos capturados: 32
Hay productos capturados.

2. Validación de estructura esperada
Todos los campos obligatorios están presentes.

3. Resumen de valores nulos por columna
sku_id             0
marca              0
precio_raw         0
formato_raw        0
rating             6
opiniones          6
tienda             0
fecha_captura      0
nombre_producto    0
categoria          0
url_fuente         0
responsable        0
texto_crudo        0
dtype: int64
No hay nulos en campos críticos.

4. Validación de duplicados
Duplicados encontrados: 0
No se detectan duplicados por sku_id y tienda.

5. Productos con rating y opiniones
Productos con rating: 26
Productos sin rating: 6

,nombre_producto,rating,opiniones,precio_raw
0,Acana Adult pienso para perros,4.8,212.0,19.99€ a 195.98€
2,Nature's Variety No Grain Adult Medium Maxi Sa...,4.7,63.0,28.59€ a 123.46€
3,Hill's Prescription Diet Food Sensitives z/d p...,4.7,195.0,41.99€ a 180.30€
4,Nature's Variety No Grain Adult Medium Maxi Po...,4.8,44.0,26.49€ a 117.58€
5,Criadores Dietetic Hipoalergénico Adulto piens...,4.6,290.0,19.99€ a 123.48€
6,Advance Veterinary Diets Hypoallergenic pienso...,4.3,43.0,30.19€ a 137.18€
7,Orijen Original pienso para perros,4.9,188.0,27.99€ a 184.22€
8,Advance Veterinary Diets Urinary pienso para p...,4.8,45.0,30.19€ a 133.26€
10,Advance Veterinary Diets Articular +7 pienso p...,4.9,34.0,27.49€ a 150.90€
11,Criadores Dietetic Adulto Obesity pienso para ...,4.6,237.0,18.99€ a 106.38€

6. Ejemplo de documento que se insertaría en MongoDB Atlas
{'sku_id': 'TD_00001', 'marca': 'Acana', 'precio_raw': '19.99€ a 195.98€', 'formato_raw': '5.76€ el kg', 'rating': 4.8, 'opiniones': 212, 'tienda': 'Tiendanimal', 'fecha_captura': '2026-05-14 22:36:27', 'nombre_producto': 'Acana Adult pienso para perros', 'categoria': 'Pienso para perros', 'url_fuente': 'https://www.tiendanimal.es/perros/pienso-para-perros/', 'responsable': 'Yahima', 'texto_crudo': '-5€ cada 35€ Patrocinado Patrocinado Acana Adult pienso para perros 4.8 estrellas con 212 opiniones 4.8 (212) Precio de 19.99€ a 195.98€ 19.99€ - 195.98€ 5.76€ el kg Desde 5.76€ / kg 6 opciones de peso Vendido por Tiendanimal Vendido por Tiendanimal Añadir al carrito'}

7. Decisión final
Los datos son suficientemente buenos para entrar al pipeline Big Data.
Puede continuar con la inserción/actualización en MongoDB Atlas.

Navegador cerrado correctamente.

# Paso 8: Insertar o actualizar datos en MongoDB Atlas

La guía del proyecto establece que el pipeline debe evitar duplicados cuando el scraper vuelva a ejecutarse sobre productos ya existentes.

Por este motivo, utilizaremos operaciones de actualización (`update`) con `upsert=True`.

## ¿Qué significa upsert?

- Si el producto NO existe → se inserta.
- Si el producto YA existe → se actualiza.

De esta manera el pipeline mantiene información persistente y reutilizable, evitando registros repetidos en MongoDB Atlas.

Además, esta estrategia permite:

- mantener históricos,
- reejecutar scrapers periódicamente,
- automatizar el pipeline,
- y asegurar consistencia de datos.ue`.

In [48]:
from pymongo import UpdateOne

operaciones = []

for producto in productos:

    operaciones.append(

        UpdateOne(

            # Condición de búsqueda del documento
            {
                "sku_id": producto["sku_id"],
                "tienda": producto["tienda"]
            },

            # Datos a actualizar
            {
                "$set": producto
            },

            # Si no existe → insertar
            upsert=True
        )
    )

# Ejecutar operaciones masivas
if operaciones:

    resultado = coleccion_raw.bulk_write(operaciones)

    print("Inserción/actualización completada correctamente")

    print(f"Productos insertados nuevos: {resultado.upserted_count}")

    print(f"Productos actualizados: {resultado.modified_count}")

else:

    print("No existen productos para insertar")

Inserción/actualización completada correctamente
Productos insertados nuevos: 32
Productos actualizados: 0

In [49]:
#validación final
total_documentos = coleccion_raw.count_documents({})

print("Total documentos en Mongo Atlas:", total_documentos)

#verificacion de documentos
for doc in coleccion_raw.find().limit(3):

    print(doc)

    print("-" * 80)

Total documentos en Mongo Atlas: 32
{'_id': ObjectId('6a064de66df289083b0fcf2e'), 'tienda': 'Tiendanimal', 'sku_id': 'TD_00001', 'categoria': 'Pienso para perros', 'fecha_captura': '2026-05-14 22:36:27', 'formato_raw': '5.76€ el kg', 'marca': 'Acana', 'nombre_producto': 'Acana Adult pienso para perros', 'opiniones': 212, 'precio_raw': '19.99€ a 195.98€', 'rating': 4.8, 'responsable': 'Yahima', 'texto_crudo': '-5€ cada 35€ Patrocinado Patrocinado Acana Adult pienso para perros 4.8 estrellas con 212 opiniones 4.8 (212) Precio de 19.99€ a 195.98€ 19.99€ - 195.98€ 5.76€ el kg Desde 5.76€ / kg 6 opciones de peso Vendido por Tiendanimal Vendido por Tiendanimal Añadir al carrito', 'url_fuente': 'https://www.tiendanimal.es/perros/pienso-para-perros/'}
--------------------------------------------------------------------------------
{'_id': ObjectId('6a064de66df289083b0fcf2f'), 'tienda': 'Tiendanimal', 'sku_id': 'TD_00002', 'categoria': 'Pienso para perros', 'fecha_captura': '2026-05-14 22:36:27', 'formato_raw': '1.27€ el kg', 'marca': 'Salvaje', 'nombre_producto': 'Salvaje Base Adultos Pollo pienso para perros', 'opiniones': None, 'precio_raw': '8.99€ a 37.98€', 'rating': None, 'responsable': 'Yahima', 'texto_crudo': '-40% en 2ª ud. Salvaje Base Adultos Pollo pienso para perros Precio de 8.99€ a 37.98€ 8.99€ - 37.98€ 1.27€ el kg Desde 1.27€ / kg 3 opciones de peso Vendido por Tiendanimal Vendido por Tiendanimal Añadir al carrito', 'url_fuente': 'https://www.tiendanimal.es/perros/pienso-para-perros/'}
--------------------------------------------------------------------------------
{'_id': ObjectId('6a064de66df289083b0fcf30'), 'tienda': 'Tiendanimal', 'sku_id': 'TD_00003', 'categoria': 'Pienso para perros', 'fecha_captura': '2026-05-14 22:36:27', 'formato_raw': '5.14€ el kg', 'marca': "Nature's", 'nombre_producto': "Nature's Variety No Grain Adult Medium Maxi Salmón pienso para perros", 'opiniones': 63, 'precio_raw': '28.59€ a 123.46€', 'rating': 4.7, 'responsable': 'Yahima', 'texto_crudo': "¡Kilos Gratis! Patrocinado Patrocinado Nature's Variety No Grain Adult Medium Maxi Salmón pienso para perros 4.7 estrellas con 63 opiniones 4.7 (63) Precio de 28.59€ a 123.46€ 28.59€ - 123.46€ 5.14€ el kg Desde 5.14€ / kg 3 opciones de peso Vendido por Tiendanimal Vendido por Tiendanimal Añadir al carrito", 'url_fuente': 'https://www.tiendanimal.es/perros/pienso-para-perros/'}
--------------------------------------------------------------------------------